tasks:
    - init: npm i
      command: npm run dev

ports:
    - port: 3001
      onOpen: ignore

    - port: 8080
      onOpen: ignore

vscode:
    extensions:
        - digitalbrainstem.javascript-ejs-support
